# Generated by Django 3.2.3 on 2021-06-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13)),
                ('nombre_cli', models.CharField(default='', max_length=50)),
                ('apellido_cli', models.CharField(default='', max_length=50)),
                ('fecha_nac', models.DateTimeField(verbose_name='Fecha de nacimiento del cliente')),
                ('correo', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50)),
                ('contrasena_val', models.CharField(max_length=50)),
            ],
        ),
    ]
