# Generated by Django 3.2.3 on 2021-07-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0002_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('gerente', 'Es gerente'), ('cocinero', 'Es cocinero'))},
        ),
    ]
